site_name: RoStrap
site_url: https://rostrap.github.io/
site_description: Reusable, unified resource networking to expedite game development on ROBLOX
site_author: Validark

repo_name: RoStrap
repo_url: https://github.com/RoStrap
edit_uri: ""

theme:
  name: 'material'
  logo: 'assets/images/RoStrap.png'
  favicon: 'assets/images/RoStrap.png'
  palette:
    primary: 'Teal'
    accent: 'Pink'
  feature:
    tabs: true
  language: 'en'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

pages:
  - Introduction: index.md
  - Getting Started: Getting-Started.md
  - Resources: Resources.md
  - Libraries:
      - Introduction: Libraries/index.md
      - Classes:
        - Enumeration: Libraries/Classes/Enumeration.md
        - PseudoInstance: Libraries/Classes/PseudoInstance.md
        - ReplicatedPseudoInstance: Libraries/Classes/ReplicatedPseudoInstance.md
      - Events:
        - Janitor: Libraries/Events/Janitor.md
        - Signal: Libraries/Events/Signal.md
      - EvLightning: Libraries/EvLightning.md
      - Debug: Libraries/Debug.md
      - Helper:
        - FastSpawn: Libraries/Helper/FastSpawn.md
        - Make: Libraries/Helper/Make.md
      - Input:
        - Keys: Libraries/Input/Keys.md
      - Interpolation:
        - Bezier: Libraries/Interpolation/Bezier.md
        - Easing: Libraries/Interpolation/Easing.md
        - Lerps: Libraries/Interpolation/Lerps.md
        - Tween: Libraries/Interpolation/Tween.md
      - Material:
        - AsymmetricTransformation: Libraries/Material/AsymmetricTransformation.md
        - RippleButton: Libraries/Material/RippleButton.md
        - ChoiceDialog: Libraries/Material/ChoiceDialog.md
        - Colors: Libraries/Material/Colors.md
        - SelectionControl: Libraries/Material/SelectionControl.md
        - Shadow: Libraries/Material/Shadow.md
        - Snackbar: Libraries/Material/Snackbar.md
      - Math:
        - Leveler: Libraries/Math/Leveler.md
        - Normal: Libraries/Math/Normal.md
        - WeightedProbabilityFunction: Libraries/Math/WeightedProbabilityFunction.md
      - Ready: Libraries/Ready.md
      - Sentry: Libraries/Sentry.md
      - Time:
        - Date: Libraries/Time/Date.md
        - SyncedPoller: Libraries/Time/SyncedPoller.md
      - Try: Libraries/Try.md
      - Utility:
        - HTMLParser: Libraries/Utility/HTMLParser.md
        - SortedArray: Libraries/Utility/SortedArray.md
        - Table: Libraries/Utility/Table.md
  - Contributing:
    - Information: Contributing/index.md
    - Website: Contributing/Website.md
    - Image Standards: Contributing/Image Standards.md

markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - footnotes

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

extra:
  social:
    - type: 'discord'
      link: 'https://discord.gg/pjJw8s4'
    - type: 'github-alt'
      link: 'https://github.com/RoStrap'
